package ar.edu.unlu.poo.enumerados;

public enum EstadoJuego {
    ESPERANDO_TURNO,
    COLOCAR_FICHA,
    SELECCIONAR_ORIGEN_MOVER,
    SELECCIONAR_DESTINO_MOVER,
    SELECCIONAR_ORIGEN_MOVER_SUPER,
    SELECCIONAR_DESTINO_MOVER_SUPER,
    SELECCIONAR_FICHA_PARA_ELIMINAR
}
