package ar.edu.unlu.poo.enumerados;

public enum EventosTablero {
    MOLINO,
    CAMBIO_EN_EL_TABLERO,
    INICIO_PARTIDA,
    JUGADOR_CONECTADO,
    FIN_PARTIDA,
    JUGADOR_SIN_FICHAS,
    JUGADOR_SIN_MOVIMIENTOS,
    FIN_PARTIDA_ABANDONO,
    PARTIDA_SUSPENDIDA,
    CAMBIO_TURNO_JUGADOR
}
