package ar.edu.unlu.poo.enumerados;

public enum EventosTablero {
    MOLINO,
    CAMBIO_EN_EL_TABLERO,
    INICIO_PARTIDA,
    JUGADOR_CONECTADO,
    NO_HAY_FICHAS_PARA_ELIMINAR,
    FIN_PARTIDA,
    JUGADOR_SIN_FICHAS,
    JUGADOR_SIN_MOVIMIENTOS,
    TURNO_JUGADOR
}
